// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiNe8liD1lmJ6TfIpzr9l96FFeRRfkVhs',
    appId: '1:1023885072511:web:1956c3cb09e8816c45874a',
    messagingSenderId: '1023885072511',
    projectId: 'graduationproject-cb209',
    authDomain: 'graduationproject-cb209.firebaseapp.com',
    storageBucket: 'graduationproject-cb209.firebasestorage.app',
    measurementId: 'G-53EDJ849JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDB-NlafrcbYHO4gNt3fKZmAINVL24Ev0',
    appId: '1:1023885072511:android:763723889487a9d445874a',
    messagingSenderId: '1023885072511',
    projectId: 'graduationproject-cb209',
    storageBucket: 'graduationproject-cb209.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0iI44JDnFr0_wlsRX91j5ZxLHI_v2JA',
    appId: '1:1023885072511:ios:44c52cd08f0789c845874a',
    messagingSenderId: '1023885072511',
    projectId: 'graduationproject-cb209',
    storageBucket: 'graduationproject-cb209.firebasestorage.app',
    iosBundleId: 'com.example.enTouch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM0iI44JDnFr0_wlsRX91j5ZxLHI_v2JA',
    appId: '1:1023885072511:ios:44c52cd08f0789c845874a',
    messagingSenderId: '1023885072511',
    projectId: 'graduationproject-cb209',
    storageBucket: 'graduationproject-cb209.firebasestorage.app',
    iosBundleId: 'com.example.enTouch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiNe8liD1lmJ6TfIpzr9l96FFeRRfkVhs',
    appId: '1:1023885072511:web:77f641914510306845874a',
    messagingSenderId: '1023885072511',
    projectId: 'graduationproject-cb209',
    authDomain: 'graduationproject-cb209.firebaseapp.com',
    storageBucket: 'graduationproject-cb209.firebasestorage.app',
    measurementId: 'G-ZHYQY7PBBJ',
  );
}
